export const SET_ADMIN_LOADING="SET_ADMIN_LOADING";
export const SET_ADMIN_SUCCESS="SET_ADMIN_SUCCESS";
export const SET_ADMIN_ERROR="SET_ADMIN_ERROR";

export const LOGIN_ADMIN_LOADING="LOGIN_ADMIN_LOADING";
export const LOGIN_ADMIN_SUCCESS="LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_ERROR="LOGIN_ADMIN_ERROR";