export const SET_ADMIN_LOADING="SET_ADMIN_LOADING";
export const SET_ADMIN_SUCCESS="SET_ADMIN_SUCCESS";
export const SET_ADMIN_ERROR="SET_ADMIN_ERROR";

export const LOGIN_ADMIN_LOADING="LOGIN_ADMIN_LOADING";
export const LOGIN_ADMIN_SUCCESS="LOGIN_ADMIN_SUCCESS";
export const LOGIN_ADMIN_ERROR="LOGIN_ADMIN_ERROR";

export const GET_PARTNERS_LOADING="GET_PARTNER_LOADING";
export const GET_PARTNERS_SUCCESS="GET_PARTNER_SUCCESS";
export const GET_PARTNERS_ERROR="GET_PARTNERS_ERROR";

export const EDIT_PARTNERS_LOADING="EDIT_PARTNER_LOADING";
export const EDIT_PARTNERS_SUCCESS="EDIT_PARTNER_SUCCESS";
export const EDIT_PARTNERS_ERROR="EDIT_PARTNERS_ERROR";

export const DELETE_PARTNERS_LOADING="DELETE_PARTNER_LOADING";
export const DELETE_PARTNERS_SUCCESS="DELETE_PARTNER_SUCCESS";
export const DELETE_PARTNERS_ERROR="DELETE_PARTNERS_ERROR";

export const ADD_PARTNERS_LOADING="ADD_PARTNER_LOADING";
export const ADD_PARTNERS_SUCCESS="ADD_PARTNER_SUCCESS";
export const ADD_PARTNERS_ERROR="ADD_PARTNERS_ERROR";
